// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiceGameClient is the client API for DiceGame service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiceGameClient interface {
	SendCommitment(ctx context.Context, in *Commitment, opts ...grpc.CallOption) (*DieThrow, error)
	SendOpening(ctx context.Context, in *Opening, opts ...grpc.CallOption) (*Acknowledgement, error)
}

type diceGameClient struct {
	cc grpc.ClientConnInterface
}

func NewDiceGameClient(cc grpc.ClientConnInterface) DiceGameClient {
	return &diceGameClient{cc}
}

func (c *diceGameClient) SendCommitment(ctx context.Context, in *Commitment, opts ...grpc.CallOption) (*DieThrow, error) {
	out := new(DieThrow)
	err := c.cc.Invoke(ctx, "/DiceGame/SendCommitment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diceGameClient) SendOpening(ctx context.Context, in *Opening, opts ...grpc.CallOption) (*Acknowledgement, error) {
	out := new(Acknowledgement)
	err := c.cc.Invoke(ctx, "/DiceGame/SendOpening", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiceGameServer is the server API for DiceGame service.
// All implementations must embed UnimplementedDiceGameServer
// for forward compatibility
type DiceGameServer interface {
	SendCommitment(context.Context, *Commitment) (*DieThrow, error)
	SendOpening(context.Context, *Opening) (*Acknowledgement, error)
	mustEmbedUnimplementedDiceGameServer()
}

// UnimplementedDiceGameServer must be embedded to have forward compatible implementations.
type UnimplementedDiceGameServer struct {
}

func (UnimplementedDiceGameServer) SendCommitment(context.Context, *Commitment) (*DieThrow, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommitment not implemented")
}
func (UnimplementedDiceGameServer) SendOpening(context.Context, *Opening) (*Acknowledgement, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOpening not implemented")
}
func (UnimplementedDiceGameServer) mustEmbedUnimplementedDiceGameServer() {}

// UnsafeDiceGameServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiceGameServer will
// result in compilation errors.
type UnsafeDiceGameServer interface {
	mustEmbedUnimplementedDiceGameServer()
}

func RegisterDiceGameServer(s grpc.ServiceRegistrar, srv DiceGameServer) {
	s.RegisterService(&DiceGame_ServiceDesc, srv)
}

func _DiceGame_SendCommitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Commitment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceGameServer).SendCommitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DiceGame/SendCommitment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceGameServer).SendCommitment(ctx, req.(*Commitment))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiceGame_SendOpening_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Opening)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceGameServer).SendOpening(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DiceGame/SendOpening",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceGameServer).SendOpening(ctx, req.(*Opening))
	}
	return interceptor(ctx, in, info, handler)
}

// DiceGame_ServiceDesc is the grpc.ServiceDesc for DiceGame service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiceGame_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DiceGame",
	HandlerType: (*DiceGameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommitment",
			Handler:    _DiceGame_SendCommitment_Handler,
		},
		{
			MethodName: "SendOpening",
			Handler:    _DiceGame_SendOpening_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/main.proto",
}
